version: "3.8"

networks:
    private:
        name: private-network
        ipam:
            config:
                - subnet: 10.9.0.0/24

services:
    main:
        build: .
        command: sleep infinity
        volumes:
            - ../..:/workspaces:cached
        networks:
            private:
                ipv4_address: 10.9.0.100

    oracle-server:
        build: ./encryption_oracle
        image: seed-image-encryption
        container_name: oracle-server
        tty: true
        cap_add:
            - ALL
        networks:
            private:
                ipv4_address: 10.9.0.80
